In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

Reason 1  Reason 2  Reason 3  Reason 4  Month value  Day of week  \
0           0         0         0         1            7            1   
1           0         0         0         0            7            1   
2           0         0         0         1            7            2   
3           1         0         0         0            7            3   
4           0         0         0         1            7            3   
5           0         0         0         1            7            4   
6           0         0         0         1            7            4   
7           0         0         0         1            7            4   
8           0         0         1         0            7            0   
9           0         0         0         1            7            0   
10          1         0         0         0            7            0   
11          1         0         0         0            7            1   
12          1         0         0         0            7            2   
13          1         0         0         0            7            2   
14          0         0         0         1            7            2   
15          1         0         0         0            7            4   
16          0         0         0         1            7            4   
17          0         0         1         0            7            0   
18          1         0         0         0            7            3   
19          0         0         0         1            8            2   
20          1         0         0         0            8            2   
21          1         0         0         0            8            0   
22          1         0         0         0            8            0   
23          0         0         0         1            8            4   
24          0         0         1         0            8            0   
25          0         0         0         1            8            0   
26          0         0         0         1            8            1   
27          0         0         0         1            8            2   
28          0         0         1         0            8            2   
29          0         0         0         1            8            4   
..        ...       ...       ...       ...          ...          ...   
670         0         0         0         1            4            1   
671         0         0         1         0            4            3   
672         1         0         0         0            4            3   
673         0         0         0         1            4            4   
674         0         0         0         1            5            0   
675         0         0         1         0            5            2   
676         0         0         0         1            5            2   
677         1         0         0         0            5            2   
678         0         0         0         1            5            2   
679         1         0         0         0            5            3   
680         0         0         0         1            5            3   
681         1         0         0         0            5            3   
682         0         0         1         0            5            4   
683         0         0         0         1            5            4   
684         0         0         0         1            5            4   
685         0         0         0         1            5            0   
686         1         0         0         0            5            1   
687         0         0         0         1            5            1   
688         0         0         0         0            5            1   
689         0         0         0         1            5            2   
690         0         0         0         0            5            2   
691         0         1         0         0            5            4   
692         1         0         0         0            5       

## CREATE TARGET

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

##### moderately absent <=3 (0 value (target))
Excessively absent >=4 (1 value (target))

In [5]:
### np.where(expression>check,on_true,on_false)

In [6]:
targets=np.where(data_preprocessed["Absenteeism Time in Hours"]>3,1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
#### using pandas it can be also done
targets=np.where(data_preprocessed["Absenteeism Time in Hours"]>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
data_preprocessed['Excessive absenteeism']=targets

In [11]:
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month value  Day of week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
#around 45 percent data is of 1 and 55 percent is of 0
###target.sum gives 1
### target.shape[0] give 0 values
###### 60-40 ratio sould be there ideally
### but here 45-55 willalso work
targets.sum()/targets.shape[0]

0.45571428571428574

In [13]:
data_wiith_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of week','Distance to Work','Daily Work Load Average'],axis=1)

##### data_wiith_targets is our check point 

In [14]:
data_wiith_targets is data_preprocessed

False

In [15]:
data_wiith_targets.iloc[:,:14]

Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1            7   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            7   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            8   
20          1         0         0         0            8   
21          1         0         0         0            8   
22          1         0         0         0            8   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            8   
27          0         0         0         1            8   
28          0         0         1         0            8   
29          0         0         0         1            8   
..        ...       ...       ...       ...          ...   
670         0         0         0         1            4   
671         0         0         1         0            4   
672         1         0         0         0            4   
673         0         0         0         1            4   
674         0         0         0         1            5   
675         0         0         1         0            5   
676         0         0         0         1            5   
677         1         0         0         0            5   
678         0         0         0         1            5   
679         1         0         0         0            5   
680         0         0         0         1            5   
681         1         0         0         0            5   
682         0         0         1         0            5   
683         0         0         0         1            5   
684         0         0         0         1            5   
685         0         0         0         1            5   
686         1         0         0         0            5   
687         0         0         0         1            5   
688         0         0         0         0            5   
689         0         0         0         1            5   
690         0         0         0         0            5   
691         0         1         0         0            5   
692         1         0         0         0            5   
693         1         0         0         0            5   
694         0         0         0         1            5   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38            

In [16]:
### more good way to select data
data_wiith_targets.iloc[:,:-1]

Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1            7   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            7   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            8   
20          1         0         0         0            8   
21          1         0         0         0            8   
22          1         0         0         0            8   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            8   
27          0         0         0         1            8   
28          0         0         1         0            8   
29          0         0         0         1            8   
..        ...       ...       ...       ...          ...   
670         0         0         0         1            4   
671         0         0         1         0            4   
672         1         0         0         0            4   
673         0         0         0         1            4   
674         0         0         0         1            5   
675         0         0         1         0            5   
676         0         0         0         1            5   
677         1         0         0         0            5   
678         0         0         0         1            5   
679         1         0         0         0            5   
680         0         0         0         1            5   
681         1         0         0         0            5   
682         0         0         1         0            5   
683         0         0         0         1            5   
684         0         0         0         1            5   
685         0         0         0         1            5   
686         1         0         0         0            5   
687         0         0         0         1            5   
688         0         0         0         0            5   
689         0         0         0         1            5   
690         0         0         0         0            5   
691         0         1         0         0            5   
692         1         0         0         0            5   
693         1         0         0         0            5   
694         0         0         0         1            5   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               

In [17]:
unscaled_inputs=data_wiith_targets.iloc[:,:-1] ###DATAFRAME

##  STANDARDZE DATA

##### StandardScaler will used to subtract the mean and divide by std. devi. variablewise(featurewise)

In [18]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler=StandardScaler()

In [19]:
### we will only scale columns we want to scale
##hence ignoring dummy variable
## we have created this custom scaler as we have by mistake also scaled dummy variable which we should have not
##but thanks to the checkpoint we can use data from there (unscaled_inputs)
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
    def fit(self,X,y=None):
        self.scaler.fit(X[self.columns])
        self.mean_=np.mean(X[self.columns])
        self.var_=np.var(X[self.columns])
        return self
    def transform(self,X,y=None,copy=None):
        init_col_order=X.columns
        X_scaled=pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_not_scaled=X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]

In [20]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [21]:
#columns_to_scale=['Month value','Day of week', 'Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index','Children', 'Pets']
columns_to_omit=['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4','Education']

In [22]:
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [23]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [24]:
### ot will calculate and store mean and Std devia. from unscaled inputs featuewise
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [25]:
### to apply absenteesim scaler it uses data from absemt... to standardize unscaled_inputs
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)  ##ndARRAY

In [26]:
###alll data has been standardize
scaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
..        ...       ...       ...       ...          ...   
670         0         0         0         1    -0.673803   
671         0         0         1         0    -0.673803   
672         1         0         0         0    -0.673803   
673         0         0         0         1    -0.673803   
674         0         0         0         1    -0.388293   
675         0         0         1         0    -0.388293   
676         0         0         0         1    -0.388293   
677         1         0         0         0    -0.388293   
678         0         0         0         1    -0.388293   
679         1         0         0         0    -0.388293   
680         0         0         0         1    -0.388293   
681         1         0         0         0    -0.388293   
682         0         0         1         0    -0.388293   
683         0         0         0         1    -0.388293   
684         0         0         0         1    -0.388293   
685         0         0         0         1    -0.388293   
686         1         0         0         0    -0.388293   
687         0         0         0         1    -0.388293   
688         0         0         0         0    -0.388293   
689         0         0         0         1    -0.388293   
690         0         0         0         0    -0.388293   
691         0         1         0         0    -0.388293   
692         1         0         0         0    -0.388293   
693         1         0         0         0    -0.388293   
694         0         0         0         1    -0.388293   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1

In [27]:
scaled_inputs.shape

(700, 11)

## SPLIT DATA INTO TRAIN AND TEST

In [28]:
from sklearn.model_selection import train_test_split

array1 training data with i/p
array2 training data with target
array3 testing data with i/p
array4 testing data with target

train_test_split(i/p,target)

In [29]:
train_test_split(scaled_inputs,targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
 4           0         0         0         1     0.182726   
 512         0         0         0         1     1.039256   
 474         0         0         0         1     0.182726   
 579         0         0         1         0    -1.530333   
 586         0         0         0         1    -1.244823   
 133         0         0         0         1    -1.530333   
 597         0         0         0         1    -1.244823   
 395         0         0         0         1    -0.959313   
 67          0         0         0         1     1.039256   
 380         0         0         0         1    -1.244823   
 252         0         0         1         0     0.468236   
 31          0         0         1         0     0.468236   
 130         0         0         1         0    -1.530333   
 179         1         0         0         0    -0.959313   
 162         1         0         0         0    -0.959313   
 491         0         0

###### train_test_split(scaled_inputs,targets,train_size=0.8) means trainig wil be done on 80% and 20% will be testing data

In [30]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

x_train contain 525 with 14 feature(excessive absenteeism)
y_train contain 525 without 14 feature(excessive absenteeism)

In [31]:
print(x_train.shape,y_train.shape) ##75%

(560, 11) (560,)


x_test contain 525 with 14 feature(excessive absenteeism)
y_test contain 525 without 14 feature(excessive absenteeism)

In [32]:
print(x_test.shape,y_test.shape)  ##25 

(140, 11) (140,)


## LOGISTIC REGRESSION

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [34]:
reg=LogisticRegression()

In [35]:
reg.fit(x_train,y_train)

C:\Users\rana\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
reg.score(x_train,y_train)

0.775

MANUALLY CHECKING THE SCORE

In [37]:
model_outputs=reg.predict(x_train)

In [38]:
model_outputs.shape

(560,)

In [39]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [40]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [41]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

true =1
false=0
sum will be equal to total entry of true

In [42]:
np.sum((model_outputs==y_train))

434

Accuracy=correct prediction/#observations

In [43]:
### we can see sklear and manual accuracy is same
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.775

## FINDING INTERCEPT AND COFFICIENTS 

In [44]:
reg.intercept_

array([-1.46547112])

In [45]:
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

##  WHENEVER WE EMPLOY SKLEARN USUALLY THE RESILTS ARE IN NDARRAY NOT IN DATAFRAME

In [46]:
scaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [47]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [48]:
feature_name=unscaled_inputs.columns.values

In [49]:
summary_table=pd.DataFrame(columns=["Feature names"],data=feature_name)
summary_table["Cofficient"]=np.transpose(reg.coef_) ### we have to transpose as nd arrays are roes not columns

In [50]:
summary_table

Feature names  Cofficient
0                 Reason 1    2.627499
1                 Reason 2    0.863386
2                 Reason 3    2.960507
3                 Reason 4    0.663907
4              Month value    0.154937
5   Transportation Expense    0.599798
6                      Age   -0.172451
7          Body Mass Index    0.275685
8                Education   -0.234525
9                 Children    0.342497
10                    Pets   -0.277514

In [51]:
summary_table.index=summary_table.index+1 ## it will shift all table by 1
summary_table.loc[0]=["Intercept",reg.intercept_[0]] ## 0 so we can extract the no 
summary_table=summary_table.sort_index()

In [52]:
## if you want to delete specific row summary_table.drop(summary_table.index[1])
# summary_table=summary_table.drop(summary_table.index[1]) ##glti se 2 baar insert ho gya tha intercept

In [53]:
summary_table

Feature names  Cofficient
0                Intercept   -1.465471
1                 Reason 1    2.627499
2                 Reason 2    0.863386
3                 Reason 3    2.960507
4                 Reason 4    0.663907
5              Month value    0.154937
6   Transportation Expense    0.599798
7                      Age   -0.172451
8          Body Mass Index    0.275685
9                Education   -0.234525
10                Children    0.342497
11                    Pets   -0.277514

##  INTERPRETTING THE COFFICIENT

In [54]:
summary_table["odds ratio"]=np.exp(summary_table.Cofficient)

In [55]:
summary_table

Feature names  Cofficient  odds ratio
0                Intercept   -1.465471    0.230969
1                 Reason 1    2.627499   13.839121
2                 Reason 2    0.863386    2.371177
3                 Reason 3    2.960507   19.307751
4                 Reason 4    0.663907    1.942367
5              Month value    0.154937    1.167585
6   Transportation Expense    0.599798    1.821751
7                      Age   -0.172451    0.841599
8          Body Mass Index    0.275685    1.317433
9                Education   -0.234525    0.790946
10                Children    0.342497    1.408460
11                    Pets   -0.277514    0.757665

In [56]:
summary_table.sort_values("odds ratio",ascending=False)

Feature names  Cofficient  odds ratio
3                 Reason 3    2.960507   19.307751
1                 Reason 1    2.627499   13.839121
2                 Reason 2    0.863386    2.371177
4                 Reason 4    0.663907    1.942367
6   Transportation Expense    0.599798    1.821751
10                Children    0.342497    1.408460
8          Body Mass Index    0.275685    1.317433
5              Month value    0.154937    1.167585
7                      Age   -0.172451    0.841599
9                Education   -0.234525    0.790946
11                    Pets   -0.277514    0.757665
0                Intercept   -1.465471    0.230969

##  TESTING THE MODEL

In [57]:
reg.score(x_test,y_test)

0.75

In [59]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba
##prob of [0,1]

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.

In [60]:
predicted_proba.shape

(140, 2)

In [64]:
###prob of getting 1 indicating absenteesim
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997

## SAVE THE MODEL

In [65]:
import pickle

In [66]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [67]:
with open('modeltraining','wb') as file:
    pickle.dump(absenteeism_scaler,file)